### ISSUE TITLE
Link apache logs to elastic search

### ISSUE THREAD

**Issue by edonadei** [edonadei/create-scaling-webapp-with-elasticsearch#2]
Using filebeat & logstash

**Comment by jeromecoffin** [comment]
La conf pour Logstash est terminé. La stack actuelle est fonctionnelle.

**Comment by jeromecoffin** [comment]
Je me mets en route pour Filebeat, toujours sur la même branch.

**Comment by edonadei** [comment]
You'll probably need to rebase since i merged my last PR
```
git rebase master isolatingELK
```

**Comment by jeromecoffin** [comment]
tkt ma biche, je gère

**Comment by jeromecoffin** [comment]
On hold, some troubles in the network between Logstash and Filebeat.
