### ISSUE TITLE
Isolating ELK infrastructure in a network

### ISSUE THREAD

**Issue by edonadei** [edonadei/create-scaling-webapp-with-elasticsearch#4]
Add a Nginx before Kibana to secure the infrastructure

**Done criteria**
- Create and isolate the ELK network
- Add the Nginx container working redirecting to the ELK internal network
- Edit the readme schema

**Comment by jeromecoffin** [comment]
C'est fait les amis. Désormais on accède au kibana sur localhost:8080. A update si nécessaire rapport au HAProxy
