### ISSUE TITLE
Backup management

### ISSUE THREAD

**Issue by edonadei** [edonadei/create-scaling-webapp-with-elasticsearch#5]
- Need to find a way for backing up the ELK

**Done criteria**
When you restart the docker stack, you need to access the same data as before

**Comment by IAmFrench** [comment]
For volumes
https://docs.docker.com/storage/volumes/#backup-restore-or-migrate-data-volumes

**Comment by IAmFrench** [comment]
For Elasticsearch
https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshot-restore.html
